INFO 2023-08-12 10:50:07,836 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-12 10:50:12,829 basehttp:212 "POST /users/login/ HTTP/1.1" 200 483
WARNING 2023-08-12 10:50:18,925 log:241 Unauthorized: /users/login/
WARNING 2023-08-12 10:50:18,926 basehttp:212 "POST /users/login/ HTTP/1.1" 401 63
INFO 2023-08-12 10:50:32,993 basehttp:212 "POST /users/login/ HTTP/1.1" 200 483
WARNING 2023-08-12 12:31:16,040 log:241 Method Not Allowed: /users/login/
WARNING 2023-08-12 12:31:16,041 basehttp:212 "GET //users/login/ HTTP/1.1" 405 45
INFO 2023-08-12 12:31:25,961 basehttp:212 "POST //users/login/ HTTP/1.1" 200 483
INFO 2023-08-12 12:38:42,558 basehttp:212 "POST //users/login/ HTTP/1.1" 200 483
INFO 2023-08-12 13:18:39,351 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\settings\dev.py changed, reloading.
INFO 2023-08-12 13:18:39,704 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-12 13:26:13,098 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\apps\host\views.py changed, reloading.
INFO 2023-08-12 13:26:13,467 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-12 13:27:45,049 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-12 13:29:30,209 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\apps\host\views.py changed, reloading.
INFO 2023-08-12 13:29:30,505 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-12 13:31:42,805 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\settings\dev.py changed, reloading.
INFO 2023-08-12 13:31:43,180 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-12 13:33:19,181 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\settings\dev.py changed, reloading.
INFO 2023-08-12 13:34:14,356 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-12 13:36:30,978 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\apps\host\views.py changed, reloading.
INFO 2023-08-12 13:36:31,332 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-12 13:38:53,616 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\apps\users\urls.py changed, reloading.
INFO 2023-08-12 13:38:53,988 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-12 13:39:51,368 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\apps\users\views.py changed, reloading.
INFO 2023-08-12 13:39:51,698 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-12 13:40:12,645 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\apps\users\views.py changed, reloading.
INFO 2023-08-12 13:40:12,983 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-12 13:41:01,219 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\apps\users\urls.py changed, reloading.
INFO 2023-08-12 13:41:01,578 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-12 13:41:11,264 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\apps\users\urls.py changed, reloading.
INFO 2023-08-12 13:41:11,617 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-12 13:41:21,262 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\apps\users\urls.py changed, reloading.
INFO 2023-08-12 13:41:21,607 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-12 13:41:34,369 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\apps\users\urls.py changed, reloading.
INFO 2023-08-12 13:41:34,711 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-12 13:41:49,602 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\apps\users\urls.py changed, reloading.
INFO 2023-08-12 13:41:49,944 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-12 13:42:48,601 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\apps\users\urls.py changed, reloading.
INFO 2023-08-12 13:42:48,974 autoreload:668 Watching for file changes with StatReloader
WARNING 2023-08-12 13:44:23,684 log:241 Not Found: /users/login/
WARNING 2023-08-12 13:44:23,685 basehttp:212 "POST //users/login/ HTTP/1.1" 404 2540
INFO 2023-08-12 13:44:46,703 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\apps\users\urls.py changed, reloading.
INFO 2023-08-12 13:44:47,061 autoreload:668 Watching for file changes with StatReloader
ERROR 2023-08-12 13:44:49,319 log:241 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\views.py", line 492, in dispatch
    request = self.initialize_request(request, *args, **kwargs)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\views.py", line 394, in initialize_request
    authenticators=self.get_authenticators(),
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\views.py", line 272, in get_authenticators
    return [auth() for auth in self.authentication_classes]
TypeError: 'type' object is not iterable
ERROR 2023-08-12 13:44:49,321 basehttp:212 "POST //users/login/ HTTP/1.1" 500 87340
INFO 2023-08-12 13:45:27,174 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\apps\users\views.py changed, reloading.
INFO 2023-08-12 13:45:27,535 autoreload:668 Watching for file changes with StatReloader
ERROR 2023-08-12 13:45:29,933 log:241 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\views.py", line 492, in dispatch
    request = self.initialize_request(request, *args, **kwargs)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\views.py", line 394, in initialize_request
    authenticators=self.get_authenticators(),
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\views.py", line 272, in get_authenticators
    return [auth() for auth in self.authentication_classes]
TypeError: 'type' object is not iterable
ERROR 2023-08-12 13:45:29,937 basehttp:212 "POST //users/login/ HTTP/1.1" 500 87340
INFO 2023-08-12 13:49:31,657 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\apps\users\urls.py changed, reloading.
INFO 2023-08-12 13:49:32,018 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-12 13:49:34,752 basehttp:212 "POST //users/login/ HTTP/1.1" 200 483
INFO 2023-08-12 13:52:03,877 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\apps\host\views.py changed, reloading.
INFO 2023-08-12 13:52:04,235 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-12 13:52:55,634 basehttp:212 "GET //host HTTP/1.1" 301 0
ERROR 2023-08-12 13:52:55,669 log:241 Internal Server Error: /host/
Traceback (most recent call last):
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\settings.py", line 177, in import_from_string
    return import_string(val)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "D:\softs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'backend '

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\views.py", line 463, in handle_exception
    exception_handler = self.get_exception_handler()
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\views.py", line 298, in get_exception_handler
    return self.settings.EXCEPTION_HANDLER
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\settings.py", line 225, in __getattr__
    val = perform_import(val, attr)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\settings.py", line 166, in perform_import
    return import_from_string(val, setting_name)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\settings.py", line 180, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'backend .utils.exceptions.custom_exception_handler' for API setting 'EXCEPTION_HANDLER'. ModuleNotFoundError: No module named 'backend '.
ERROR 2023-08-12 13:52:55,672 basehttp:212 "GET /host/ HTTP/1.1" 500 151944
INFO 2023-08-12 13:54:22,687 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\settings\dev.py changed, reloading.
INFO 2023-08-12 13:54:23,053 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-12 13:54:26,251 basehttp:212 "GET //host HTTP/1.1" 301 0
WARNING 2023-08-12 13:54:26,263 log:241 Unauthorized: /host/
WARNING 2023-08-12 13:54:26,264 basehttp:212 "GET /host/ HTTP/1.1" 401 43
INFO 2023-08-12 13:55:09,450 basehttp:212 "GET //host HTTP/1.1" 301 0
WARNING 2023-08-12 13:55:09,456 log:241 Unauthorized: /host/
WARNING 2023-08-12 13:55:09,457 basehttp:212 "GET /host/ HTTP/1.1" 401 43
INFO 2023-08-12 13:55:37,844 basehttp:212 "GET //host HTTP/1.1" 301 0
WARNING 2023-08-12 13:55:37,847 log:241 Unauthorized: /host/
WARNING 2023-08-12 13:55:37,848 basehttp:212 "GET /host/ HTTP/1.1" 401 43
INFO 2023-08-12 13:56:41,343 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\apps\users\views.py changed, reloading.
INFO 2023-08-12 13:56:41,704 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-12 13:59:34,095 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\apps\host\views.py changed, reloading.
INFO 2023-08-12 13:59:34,545 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-12 13:59:37,521 basehttp:212 "GET //host HTTP/1.1" 301 0
ERROR 2023-08-12 13:59:37,546 log:241 Internal Server Error: /host/
Traceback (most recent call last):
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\views.py", line 492, in dispatch
    request = self.initialize_request(request, *args, **kwargs)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\views.py", line 394, in initialize_request
    authenticators=self.get_authenticators(),
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\views.py", line 272, in get_authenticators
    return [auth() for auth in self.authentication_classes]
TypeError: 'type' object is not iterable
ERROR 2023-08-12 13:59:37,548 basehttp:212 "GET /host/ HTTP/1.1" 500 87746
ERROR 2023-08-12 14:00:42,607 log:241 Internal Server Error: /host/
Traceback (most recent call last):
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\views.py", line 492, in dispatch
    request = self.initialize_request(request, *args, **kwargs)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\views.py", line 394, in initialize_request
    authenticators=self.get_authenticators(),
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\views.py", line 272, in get_authenticators
    return [auth() for auth in self.authentication_classes]
TypeError: 'type' object is not iterable
ERROR 2023-08-12 14:00:42,608 basehttp:212 "GET //host/ HTTP/1.1" 500 87593
ERROR 2023-08-12 14:02:09,539 log:241 Internal Server Error: /host/
Traceback (most recent call last):
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\views.py", line 492, in dispatch
    request = self.initialize_request(request, *args, **kwargs)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\views.py", line 394, in initialize_request
    authenticators=self.get_authenticators(),
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\views.py", line 272, in get_authenticators
    return [auth() for auth in self.authentication_classes]
TypeError: 'type' object is not iterable
ERROR 2023-08-12 14:02:09,540 basehttp:212 "GET /host/ HTTP/1.1" 500 88361
WARNING 2023-08-12 14:02:10,256 log:241 Not Found: /favicon.ico
WARNING 2023-08-12 14:02:10,257 basehttp:212 "GET /favicon.ico HTTP/1.1" 404 2325
INFO 2023-08-12 14:06:05,730 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\apps\host\views.py changed, reloading.
INFO 2023-08-12 14:06:06,113 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-12 14:06:09,462 basehttp:212 "GET /host/ HTTP/1.1" 200 5137
INFO 2023-08-12 14:06:09,489 basehttp:212 "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
INFO 2023-08-12 14:06:09,489 basehttp:212 "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
INFO 2023-08-12 14:06:09,492 basehttp:212 "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
INFO 2023-08-12 14:06:09,492 basehttp:212 "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
INFO 2023-08-12 14:06:09,493 basehttp:212 "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
INFO 2023-08-12 14:06:09,494 basehttp:212 "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
INFO 2023-08-12 14:06:09,494 basehttp:212 "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
INFO 2023-08-12 14:06:09,494 basehttp:212 "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
INFO 2023-08-12 14:06:09,495 basehttp:212 "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
INFO 2023-08-12 14:06:09,495 basehttp:212 "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
INFO 2023-08-12 14:06:09,498 basehttp:212 "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
INFO 2023-08-12 14:06:15,470 basehttp:212 "GET //host/ HTTP/1.1" 200 19
INFO 2023-08-12 14:16:07,731 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\apps\host\views.py changed, reloading.
INFO 2023-08-12 14:16:08,074 autoreload:668 Watching for file changes with StatReloader
WARNING 2023-08-12 14:16:12,464 log:241 Unauthorized: /host/
WARNING 2023-08-12 14:16:12,464 basehttp:212 "GET //host/ HTTP/1.1" 401 43
INFO 2023-08-12 14:16:21,633 basehttp:212 "POST //users/login/ HTTP/1.1" 200 483
WARNING 2023-08-12 14:16:38,040 log:241 Unauthorized: /host/
WARNING 2023-08-12 14:16:38,042 basehttp:212 "GET //host/ HTTP/1.1" 401 43
INFO 2023-08-12 14:16:43,850 basehttp:212 "POST //users/login/ HTTP/1.1" 200 483
INFO 2023-08-12 14:16:45,330 basehttp:212 "POST //users/login/ HTTP/1.1" 200 483
INFO 2023-08-12 14:16:46,731 basehttp:212 "POST //users/login/ HTTP/1.1" 200 483
INFO 2023-08-12 14:18:21,460 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\apps\users\views.py changed, reloading.
INFO 2023-08-12 14:18:21,824 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-12 14:20:40,837 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\apps\users\views.py changed, reloading.
INFO 2023-08-12 14:20:41,198 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-12 14:21:04,326 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\apps\users\views.py changed, reloading.
INFO 2023-08-12 14:21:04,673 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-12 14:21:09,093 basehttp:212 "POST //users/login/ HTTP/1.1" 200 483
WARNING 2023-08-12 14:21:27,361 log:241 Unauthorized: /host/
WARNING 2023-08-12 14:21:27,362 basehttp:212 "GET //host/ HTTP/1.1" 401 43
INFO 2023-08-12 14:23:34,076 basehttp:212 "POST //users/login/ HTTP/1.1" 200 483
INFO 2023-08-12 14:24:15,115 basehttp:212 "GET //host/ HTTP/1.1" 200 19
INFO 2023-08-12 14:48:18,376 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\apps\users\views.py changed, reloading.
INFO 2023-08-12 14:48:18,761 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-13 10:50:24,838 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\apps\users\views.py changed, reloading.
